NewsDeskNew/NewsDeskNew/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('desk.urls')),
    path('accounts/', include('accounts.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

NewsDeskNew/desk/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', PostListView.as_view(), name='MainPage'),
    path('post/<int:pk>/', post_review, name='PostReview'),
    path('post/create/', PostCreateView.as_view(), name='Create'),
    path('post/update/<int:pk>', PostUpdateView.as_view(), name='Update'),
    path('post/delete/<int:pk>', PostDeleteView.as_view(), name='Delete'),
    path('post/delete_image/<int:pk>', delete_image, name='delete_image'),
    path('post/delete_video/<int:pk>', delete_video, name='delete_video'),
]

NewsDeskNew/desk/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import ForeignKey
from embed_video.fields import EmbedVideoField
from django.utils.translation import gettext_lazy as _

# Create your models here.

CATEGORY_CHOICE = [
    ("TA", "Танки"),
    ("HE", "Хилы"),
    ("DD", "ДД"),
    ("TR", "Торговцы"),
    ("GM", "Гильдмастеры"),
    ("QG", "Квестгиверы"),
    ("BS", "Кузнецы"),
    ("SK", "Кожевники"),
    ("AL", "Зельевары"),
    ("SM", "Мастера заклинаний"),
]


class User(AbstractUser):
    email = models.EmailField(unique=True)
    is_verified = models.BooleanField(default=False)
    email_conf_code = models.CharField(max_length=6, blank=True, null=True)
    users_comments = models.BooleanField(default=True, verbose_name="Новые комментарии")
    about_sub = models.BooleanField(default=False, verbose_name="Новости сайта")
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    
    def __str__(self):
        return f'{self.username}'


class Post(models.Model):
    title = models.CharField(max_length=200, verbose_name=_('Заголовок поста'))
    text = models.TextField(verbose_name=_('Содержание поста'))
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('Автор поста'))
    category = models.CharField(max_length=2, choices=CATEGORY_CHOICE, verbose_name=_('Категория поста'))
    datecreation = models.DateTimeField(auto_now_add=True)
    
    def preview(self):
        return self.text[0:123] + '...'
    
    def category_name(self):
        for category in CATEGORY_CHOICE:
            if self.category == category[0]:
                return category[1]
            
    def __str__(self):
        return f'{self.title.title()}'
    
    
class Image(models.Model):
    file = models.ImageField(upload_to='desk/gallery/images', verbose_name=_('Картинка'))
    post = ForeignKey(Post, on_delete=models.CASCADE, verbose_name=_('Пост'))
    
    
class Video(models.Model):
    url = EmbedVideoField(verbose_name=_("Ссылка на Видео"))
    post = ForeignKey(Post, on_delete=models.CASCADE, verbose_name=_('Пост'))
    
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name=_('Пост'))
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('Автор комментария'))
    text = models.TextField(verbose_name=_('Содержание комментария'))
    datecreation = models.DateTimeField(auto_now_add=True)
    is_confirmed = models.BooleanField(default=False, verbose_name='Подтвержденный комментарий')
    
    def __str__(self):
        return f'{self.text}'
    
    

NewsDeskNew/templates/Create.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% load custom_filters %}
{% load custom_tags %}

{% block title %}
    Создание/Редактирование поста
{% endblock title %}
{% block content %}
<form enctype="multipart/form-data" class="container" method="post" id="post_form">
    {% csrf_token %}
    <div class="card">
        <div class="card-header card-header-secondary">
            <h4 class="card-title">{% trans 'Добавить пост' %}</h4>
        </div>
        {% for field in form %}
            <div class="form-group card-body">
                <label>{{field.label}}</label>
                {% if field.field.required %}
                    <span class="required">*</span>
                {% endif %}

                {{field}}
            </div>
        {% endfor %}
    </div>
    {% with named_formsets.images as formset %}
        {{ formset.management_form }}
        <script type="text/html" id="images-template">
            <tr id="images-__prefix__" class= hide_all>
                {% for fields in formset.empty_form.hidden_fields %}
                    {{ fields }}
                {% endfor %}

                {% for fields in formset.empty_form.visible_fields %}
                    <td>{{fields}}</td>
                {% endfor %}
            </tr>
        </script>
        <div class="table-responsive card mt-4">
            <div class="card-header card-header-secondary">
                <h4 class="card-title">{% trans 'Добавить изображение' %}</h4>
            </div>
            <table class="table card-body">
                <thead class="text-secondary">
                    <th>{% trans 'Изображение' %} <span class="required">*</span></th>
                    <th>{% trans 'Удаление' %}</th>
                </thead>
                <tbody id="item-images">
                    {% for formss in formset %}
                        {{ formss.management_form }}
                        <tr id="images-{{ forloop.counter0 }}" class= hide_all>
                            {{ formss.id }}
                            {% for field in formss.visible_fields %}
                                <td>
                                    {{ field }}
                                </td>
                            {% endfor %}
                            {% if formss.instance.pk %}
                                <td>
                                    <a class="btn btn-danger" href="{% url 'delete_image' formss.instance.pk %}">{% trans 'Удалить' %}</a>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <a href="#" id="add-image-button" class="btn btn-secondary add-images">{% trans 'Добавить' %}</a>
        </div>
    {% endwith %}
    {% with named_formsets.video as formset %}
        {{ formset.management_form }}
        <script type="text/html" id="video-template">
            <tr id="video-__prefix__" class= hide_all>
                {% for fields in formset.empty_form.hidden_fields %}
                    {{ fields }}
                {% endfor %}

                {% for fields in formset.empty_form.visible_fields %}
                    <td>{{ fields }}</td>
                {% endfor %}
            </tr>
        </script>
        <div class="table-responsive card mt-4">
            <div class="card-header card-header-secondary">
                <h4 class="card-title">{% trans 'Добавить видео' %}</h4>
            </div>
            <table class="table card-body">
                <thead class="text-secondary">
                    <th>{% trans 'Видео' %} <span class="required">*</span></th>
                    <th>{% trans 'Удаление' %}</th>
                </thead>
                <tbody id="item-video">
                    {% for formss in formset %}
                        {{ formss.management_form }}
                        <tr id="video-{{ forloop.counter0 }}" class= hide_all>
                            {{ formss.id }}
                            {% for field in formss.visible_fields %}
                                <td>
                                    {{field}}
                                </td>
                            {% endfor %}
                            {% if formss.instance.pk %}
                                <td>
                                    <a class="btn btn-danger" href="{% url 'delete_video' formss.instance.pk %}">{% trans 'Удалить' %}</a>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <a href="#" id="add-video-button" class="btn btn-secondary add-video">{% trans 'Добавить' %}</a>
        </div>
    {% endwith %}
    <div class="form-group">
            <button type="submit" class="btn btn-secondary btn-block">{% trans 'Подтвердить' %}</button>
        </div>
</form>
{% endblock content %}

NewsDeskNew/templates/Delete.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% load custom_filters %}
{% load custom_tags %}
{% block title %}
Удаление поста
{% endblock title %}
{% block content %}
<h1>{% trans 'Удаление поста' %}</h1>
<form action="" method="post">
    {% csrf_token %}
    <p>{% trans 'Удаляем пост' %}: "{{ object }}"?</p>
    <input type="submit" value="{% trans 'Удалить' %}"/>
</form>
{% endblock content %}

NewsDeskNew/templates/MainPage.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% load static %}
{% load custom_filters %}
{% load custom_tags %}
{% block title %}
Объявления
{% endblock title %}
{% block content %}
<h1>{% trans 'Все объявления' %}</h1>
    {% if main %}
        <table>
            <tr>
                <td>{% trans 'Картинка' %}</td>
                <td>{% trans 'Заголовок' %}</td>
                <td>{% trans 'Дата публикации' %}</td>
                <td>{% trans 'Содержание' %}</td>
                <td>{% trans 'Действия' %}</td>
            </tr>
            {% for post in main %}
            <tr>
                <td>{% if post|is_image_exist %}
                        <img class="card-img-top" src="{{ post|preview }}"/>
                    {% else %}
                        <img class="card-img-top" src={% static 'img/empty.jpg' %} />
                    {% endif %}
                </td>
                <td>{{ post.title}}</td>
                <td>{{ post.datecreation|date:'d M Y'}}</td>
                <td>{{ post.text|truncatechars:20 }}</td>
                <td>
                    <a href="{% url 'PostReview' pk=post.id %}">{% trans 'Детали' %}</a>
                    {% if perms.NewsDeskNew.change_post %}
                    <a href="{% url 'Update' post.id %}">{% trans 'Изменить' %}</a>
                    {% endif %}
                    {% if perms.NewsDeskNew.delete_post %}
                    <a href="{% url 'Delete' post.id %}">{% trans 'Удалить' %}</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
            <h2>{% trans Новостей нет!' %</h2>
    {% endif %}
<footer>
    {# Предыдущие страницы #}
    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {# Текущая страница #}
    {{ page_obj.number }}

    {# Следующие страницы #}
    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
</footer>
{% endblock content %}

NewsDeskNew/templates/PersonalCabinet.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% load i18n %}
{% block title %}
Личный кабинет
{% endblock title %}
{% block content %}
<h1>{% trans 'Личный кабинет' %}: {{ user.username }}</h1>
<div class="container">
    <div>
        <p>{% trans 'Получать новости о нас' %}</p>
        {% if user.about_sub %}
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="about_unsub" value="{{ user.pk }}"/>
            <input type="submit" value="{% trans 'Отписаться' %}">
        </form>
        {% else %}
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="about_sub" value="{{ user.pk }}"/>
            <input type="submit" value="{% trans 'Подписаться' %}">
        </form>
        {% endif %}
    </div>
    <div>
        <p>{% trans 'Уведомления об откликах' %}:</p>
        {% if user.users_comments %}
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="comment_notif_unsub" value="{{ user.pk }}"/>
            <input type="submit" value="{% trans 'Не получать' %}">
        </form>
        {% else %}
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="comment_notif_sub" value="{{ user.pk }}"/>
            <input type="submit" value="{% trans 'Получать' %}">
        </form>
        {% endif %}
    </div>
    {% if user.is_staff %}
    <div>
        <a href="{% url 'Postman' %}">{% trans 'Новостная рассылка' %}</a>
    </div>
    {% endif %}
</div>
<div>
    <form action="{% url 'Logout' %}" method="post" >
        {% csrf_token %}
        <input type="submit" value="{% trans 'Выход' %}">
    </form>
</div>
<div>
    <p>{% trans 'Новые комментарии' %}</p>
</div>
<div>
    {% for post in posts %}
        {% if post.pk|is_comments_exist %}
        {{ post.title }}
            {% for comment in comments %}
                {% if comment.post == post and not comment.is_confirmed %}
                    <div>
                        <div>
                            <p>
                                {% trans 'Пользователь' %}:
                                {{ comment.author }}
                            </p>
                            <p>
                                {% trans 'Дата' %}:
                                {{ comment.datecreation|date:'d M Y' }}
                            </p>
                            <p>
                                {% trans 'Содержание' %}:
                                {{ comment.text }}
                            </p>
                            <p>
                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="agree" value="{{ comment.pk }}"/>
                                <input type="submit" value="{% trans 'Принять' %}">
                            </form>
                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="decline" value="{{ comment.pk }}"/>
                                <input type="submit" value="{% trans 'Отклонить' %}">
                            </form>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endfor %}
</div>

{% endblock content %}

NewsDeskNew/templates/PostReview.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% load custom_filters %}
{% load custom_tags %}
{% load embed_video_tags %}
{% block title %}
{% trans 'Объявление' %}
{% endblock title %}
{% block content %}
    <h1>{% trans 'Заголовок' %}: {{ post.title }}</h1>
    <h2>{% trans 'Дата' %}: {{ post.datecreation|date:'d M Y' }}</h2>
    {% if post|is_image_exist %}
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for image in post|get_image %}
                    <img style="max-width: 600px" src={{image.file.url}} />
                {% endfor %}
            </div>
        </div>
    {% endif %}
    {% if post|is_video_exist %}
        <div class="container px-4 px-lg-5 mt-5 justify-content-center">
            <div class="row gx-4 gx-lg-3 row-cols-2 row-cols-md-3 row-cols-xl-3 justify-content-center">
                <p>{% trans 'Видео' %}</p>
                {% for vid in post|get_video %}
                    {% video vid.url "640x360" %}
                {% endfor %}
            </div>
        </div>
    {% endif %}
    <p>
        {% trans 'Содержание' %}:
        {{ post.text }}
    </p>
    <div class="container px-4 px-lg-5">
        <div class="text-center">
            <h1>
                {% trans 'Комментарии' %}
            </h1>
        </div>
    </div>
    {% if user_verification %}
        <form method="post">
            <div class="container px-4 px-lg-5 mt-5 justify-content-center">
                {% csrf_token %}
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 mt-3 justify-content-center">
                    <textarea name="text" style="height: 200px; width: 600px; outline: 5px black solid"></textarea>
                </div>
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 mt-3 justify-content-center">
                    <button type="submit">{% trans 'Отправить' %}</button>
                </div>
            </div>
        </form>
    {% endif %}

    <div class="container px-4 px-lg-5 mt-5 justify-content-center">
        {% for comment in comments %}
            {% if comment.is_confirmed %}
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 mt-3 justify-content-center">
                    <div class="card h-100" style="height: 200px; width: 1000px; outline: 5px black solid;">
                        <p>
                            {% trans 'Пользователь' %}:
                            {{ comment.author }}
                        </p>
                        <p>
                            {% trans 'Дата' %}:
                            {{ comment.datecreation }}
                        </p>
                        <p>
                            {% trans 'Содержание' %}:
                            {{ comment.text }}
                        </p>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock content %}

NewsDeskNew/templates/Postman.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% block title %}
{% trans 'Почтальон' %}
{% endblock title %}
{% block content %}
<h1>{% trans 'Почтальон' %}</h1>
<form>
    {% csrf_token %}
    <div class="container">
        <div>
            <p>{% trans 'Тема' %}:</p>
            <input type="text" name="msg_title_of_post"/>
        </div>
        <div>
            <p>{% trans 'Содержание' %}:</p>
            <input type="text" name="msg_text_of_post"/>
        </div>
        <div>
            <button type="submit">{% trans 'Разослать' %}</button>
        </div>
    </div>
</form>
{% endblock content %}